name: Python CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - run: |
          cd $GITHUB_WORKSPACE
          pip install .

      - run: pip show tx

      - run: |
          export PYTHONPATH=$PYTHONPATH:$GITHUB_WORKSPACE
          coverage run -m pytest -vv
          coverage report
          coverage xml

      - uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage.xml

      - name: Install Doxygen
        run: sudo apt-get update && sudo apt-get install -y doxygen
          
      - name: Generate Doxygen documentation
        run: |
          if [ ! -f Doxyfile ]; then
            doxygen -g Doxyfile
          fi
          
          FILES=$(find ./ -name "*.py" | tr '\n' ' ')
          echo "INPUT = $FILES" >> Doxyfile

          sed -i "s|^INPUT .*|INPUT = ./tx ./channel ./examples ./gui|" Doxyfile
          sed -i "s|^OUTPUT_DIRECTORY .*|OUTPUT_DIRECTORY = html|" Doxyfile
          sed -i "s|^GENERATE_HTML .*|GENERATE_HTML = YES|" Doxyfile
          sed -i "s|^RECURSIVE .*|RECURSIVE = YES|" Doxyfile
          
          doxygen Doxyfile

      - name: Upload Doxygen docs
        uses: actions/upload-artifact@v4
        with:
          name: doxygen-html-docs
          path: html/html
          